travis:
  secure:
    BINSTAR_TOKEN: B/r/4L+Uz3QauzaSX/sbI4/OEDY82hP6i45rmac3Yj145uTz5tPMrJPu9Rdf9SCk62i4iDfmT3FxCdghFfHwVwKVJFUESbOEBK/CXz+sOER0OVfi+V4SKt2PdO8WkUcTIAhL77SFTG/rBfWphgVkVt/Je4h5x1ZrW3RhRhWh8RojcUfpR/tikcWQiwx3b8lohYYDjVb+0KuxQr22RC3F5/vIlSAn1OswHMO/1RNEhshJeEVwzW8QzlDV62Hl9+fWiMGkSmOwIrfUsZDQnQl0oLps/176j95vRyXJoP52o+mdEqUT63Ro7Df7D02ffbFQJMOqaEcNwy1KNqu4jFp+z2a4YuMAlcvWhZVERmegn7LJ5AiOxpFkYP/JySu5z1Tz1yKDrN53IOMm71ZoPoFhTmeL6BzkgUFNyg5UES6bycfyE2g278hl3jrYFBw049QCjaVNJrDlO4SMDNZHFCx+nX44sG6fo0bdnnvgjSHMzSqVb6XgnP1L4DzdtHMLewvSpX7gpo/uhSTIBOd7pKCPWWAQMX2UG+FGL/cSgCHx/iFppzyrePDFj+jckGWr+kCJcPq8fiix5JsqiA82/P8zsxB5oKBjOVAPgtIJGrCAv61ud3vCcwfZOvCUHu6T5ygfObzS/GjL8gFbHtTVElv7ElRIu/Envcb32bC9gnUJG04=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
