travis:
  secure:
    BINSTAR_TOKEN: zkDByrEcsEBsfVhQyD3mxNAgMS7BG9AQiN9tbPMfQM5F+XlT0JG7TY0PhypGXPhhGROm7Wo2wEWNDKjhnwTlJIXmO/ag6UQcfAylAO/yvYqjr9XEO43RuG+Qcf/s4gcXeGTbOJRnA0YmIS7cKqvhep8M/+sw69vs5E+G/Vo7eZFIDDG3DHsNpJZ/g5m6jFG+y00SF9/8SgKNazVR7s/EzvZmCyIZ7oj7MxzJYdk7kis2HAPH5tGSs3lF3yLXRZFWqs0Ozt+dj0WKGrmChsJzld9nJ+TzxZtHqNiKdV/q3Dy6TPkAXEZlVj9LX4Gsv1nHXUNzlkO2WqmjDPC/OFEbHJLj3fRTosOcQEkMSfIS1rOV3cx1sipQTuGuZ3qzw6jv7u4wpo9NKnX+SrQo5i5Io8/2x6CQ/DUDFgN0pwi/JWKLZNukBaVfaTssn88Pe76E+DdGQ8S1oX1jPAYCzBM5oq75gAvUvP36cIK6+gtp3IkPYvo3qjwayQ8Bm7Kk35DOUF4onpjUs4QrzePpQO3NklZN6IpbqY9PiQYCvoP/B+X4xYOo3Vf5UvMX5Vi/FMPhGLx6nwAMyr/rbQeMN/I0GvXihHkUF1awwtomHmUPoTImyIsSvPBtIRs6IzeSR7ZSjE0KMvpl6X1X9vl59A9NA6gBckoO9N6I/6/Ek9GH708=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
